export const GENDER = {
    MALE: "MALE",
    FEMALE: "FEMALE",
    OTHER: "OTHER",
};

export const USER_STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
};

export const ROLE = {
    ADMIN: "ADMIN",
    MANAGER: "MANAGER",
    SUPERVISOR: "SUPERVISOR",
    CASHIER: "CASHIER",
    RECEPTIONIST: "RECEPTIONIST",
    WAITSTAFF: "WAITSTAFF",
    BARISTA: "BARISTA",
    HEAD_CHEF: "HEAD_CHEF",
    SOUS_CHEF: "SOUS_CHEF",
    COMMIS_CHEF: "COMMIS_CHEF",
    CLEANER_STAFF: "CLEANER_STAFF",
    GUARD: "GUARD",
    GUEST: "GUEST",
};
